### ISSUE TITLE
This Extension is Too Amazing!

### ISSUE THREAD

**Issue by Jitsusama** [anhthang/raycast-pokedex#2]
I'm a user of this extension and I have a complaint.

It is too awesome. Seriously, why did you dial it up to 11? It has literally ruined my life! All I do all day is use it to look up Pokemon. It has single-handedly tanked my productivity.

Please, for the love of all that is holy, make it less awesome!

Seriously though, I had to say that this made my day and I couldn't think of a better way to let you know. You're awesome!

**Comment by anhthang** [comment]
I'm glad you're enjoying my extension so much! It sounds like you've become a bit too attached to the world of Pokémon. Perhaps it's time for a digital detox?

But seriously, I'm happy to hear that my extension has made your day. Keep exploring the wonderful world of Pokémon!

**And, I've added new details for type effectiveness in the upcoming release. So, stay tuned for that!**

**Comment by Jitsusama** [comment]
> I'm glad you're enjoying my extension so much! It sounds like you've become a bit too attached to the world of Pokémon. Perhaps it's time for a digital detox?

I'll let it go on my death bed, and not a moment sooner! 😆

> But seriously, I'm happy to hear that my extension has made your day. Keep exploring the wonderful world of Pokémon!
> 
> **And, I've added new details for type effectiveness in the upcoming release. So, stay tuned for that!**

Excited Pikachu face!
